---
title: "Logit"
author: "Aaron Rockwell"
date: "2/25/2020"
output: pdf_document
---

```{r loadfile}
library(ResourceSelection)
library(MASS)
library(logistf)
library(dplyr)
library(MuMIn)
library(caret)

df = data.frame(read.csv("train.csv"))

head(df)
```

```{r train_test}
smp_size = floor(0.20 * nrow(df))

set.seed(123)
train_ind = sample(seq_len(nrow(df)), size = smp_size)  
train = df[-train_ind,]
selection = df[train_ind,]

train_ind = sample(seq_len(nrow(train)), size = smp_size)  
train = train[-train_ind,]
validation = train[train_ind,]

# Now I have three splits from train.csv = 20% validation and selection, 60% train
nrow(train)
nrow(selection)
nrow(validation)
```


```{r log_reg}
mylogit <- glm(loan_status_Fully_Paid ~ ., data = selection, family = "binomial")
```


```{r log_stepwise}
mylogit.step = stepAIC(mylogit, direction = "forward")
```

```{r select_features}
# select if p value is < .05
features_keep = summary(mylogit.step)$coefficients[,"Pr(>|z|)", drop=FALSE]
zfeatures = as.data.frame(features_keep)
zfeatures = subset(zfeatures, `Pr(>|z|)` < .05)
zfeatures
```

```{r rerun_reg}
train_all = subset(train, select = c(rownames(zfeatures), 'loan_status_Fully_Paid'))
mylogit <- glm(loan_status_Fully_Paid ~ ., data = train_all, family = "binomial")
```


```{r rerun_reg}
summary(mylogit) 
```

```{r prediction_scores_ McFaddenR2}
# No Hosmer and Lemeshow goodness of fit (GOF) test not great with large data sets. Went with McFadden Psuedo R^2

nullmod <- glm(loan_status_Fully_Paid ~ 1, data=train, family="binomial")
1-logLik(mylogit)/logLik(nullmod)

```


```{r predict_holdout}
# validation set has not been seen during training, will use this set for final strategy selection
predict_sample = predict.glm(mylogit, validation, type = "response")

validation['predict'] = predict_sample

# clean out NAs from split
validation = validation[complete.cases(validation$sub_grade_A1), ]

write.csv(validation, "validation.csv")

```

```{r predict_test}
# add predictions to test set
test = data.frame(read.csv("test.csv"))
test['predicted_values'] =  predict.glm(mylogit, test, type = "response")
head(test)
```

```{r export_coef}

write.csv(summary(mylogit)$coefficients, "logit_coefs.csv")
write.csv(test, "test_with_predicted.csv")
```